### ISSUE TITLE
マルチアカウント対応希望

### ISSUE THREAD

**Issue by aroerina** [arrow2nd/twnyan#15]
twnyan使ってみましたが、とてもカラフルでわかりやすい良いクライアントですね！
自分はマルチアカウントで運用しているのですが
twnyanが対応するようになるとと嬉しいです

**Comment by arrow2nd** [comment]
ご提案、ありがとうございます。

設計上、どこまで実現できるか分かりませんが、面白そうなのでやってみます！

**Comment by aroerina** [comment]
ありがとうございます。よろしくお願いします🙇

**Comment by arrow2nd** [comment]
こちらの [v1.8.0](https://github.com/arrow2nd/twnyan/releases/tag/v1.8.0) にて、マルチアカウントに対応しました！

併せて [コマンドのドキュメント](https://github.com/arrow2nd/twnyan/blob/main/docs/ja/commands/index.md) も再整備しましたので、よろしければご確認ください。

**Comment by aroerina** [comment]
対応いただき感謝です〜！
ver1.8.2でアカウント指定でツイートできることを確認いたしました。
のですが
switchでアカウントが切り替わらないようです、切り替えてもmainでツイート、TLの表示もmainのものとなってしまいます

**Comment by arrow2nd** [comment]
こちらこそ、ご提案ありがとうございました！

そちらの件について確認してみましたが、手元では問題なく動いているようでした。

![image](https://user-images.githubusercontent.com/44780846/167832046-0a7d3024-990c-4540-887e-38d5fa93b3ee.png)

`switch` コマンドは対話モードでのみ使用可能で、起動時にアカウントを指定する場合は `twnyan --account <ユーザID>` とする仕様になっているのですが、「対話モードで `switch` コマンドを使用してもアカウントが切り替わらない」ということでしょうか？

**Comment by aroerina** [comment]
そういう仕様だったのですね。対話モードじゃない時に試してました
でしたら問題ないです

**Comment by arrow2nd** [comment]
わかりにくい仕様で申し訳ないです…。
